pull_request_rules:
  - name: "PR Reset with New Commit"
    conditions:
      - label=mergify-exploit
      - base=main
    actions:
      close:
        message: "PR closed for commit rewriting."
      backport:
        branches:
          - main
