pull_request_rules:
  - name: "Bypass All Required Status Checks with 'mergify-one-check'"
    conditions:
      - label=mergify-one-check
      
    actions:
      merge:
        method: squash