name: ci/unit-tests  # This is the important part for the status check name

on:
  pull_request:
    branches: [ main ] # Or your protected branch name

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Example - adjust for your language)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Or your language's package manager

      - name: Run unit tests
        run: npm test     # Or your language's test command
